spring:
  application:
    name: smart-news
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY:dummy-key}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
